kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gravity-azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - uid=1001
  - gid=1001
  - mfsymlinks
  - actimeo=30
parameters:
  skuName: Standard_LRS
