apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-init
data:
  mssql_init.sql: "create DATABASE TestDB;\n
  GO\n\n
  USE TestDB;\n
  GO\n\n
  create table users(\n\t
  id varchar(50) primary key,\n\t
  name varchar(50),\n\t
  nickname varchar(50),\n\t
  gender int,\n\t
  disabled bit,\n\t
  username varchar(50),\n\t
  password varchar(256),\n\t
  address text,\n\t
  email varchar(80),\n\t
  phone varchar(50)\n
  );\n  
  GO\n\n
  EXEC sys.sp_cdc_enable_db\n
  GO\n\n
  EXEC sys.sp_cdc_enable_table\n
  @source_schema = N'dbo',\n
  @source_name = N'users',\n
  @role_name = NULL\n
  GO\n"

#/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 1qaz@WSX -i /docker-entrypoint-initdb.d/init.sql


