apiVersion: v1
kind: Service
metadata:
  name: demo3-mysql
  labels:
    app: gravity
spec:
  ports:
    - port: 3306
      name: tcp
      protocol: TCP
  selector:
    name: demo3-mysql
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: demo3-mysql
  labels:
    name: demo3-mysql
spec:
  containers:
    - image: mysql:8.0
      name: demo3-mysql
      env:
        - name: "MYSQL_DATABASE"
          value: "gravity"
        - name: "MYSQL_USER"
          value: "mysql"
        - name: "MYSQL_PASSWORD"
          value: "1qaz@WSX"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "1qaz@WSXROOT"
      volumeMounts:
      - mountPath: /docker-entrypoint-initdb.d
        name: mysql-init
      ports:
        - containerPort: 3306
          name: tcp
  volumes:
  - name: mysql-init
    configMap:
      name: demo3-mysql-init
      items:
      - key: mysql_init.sql
        path: init.sql
